### ISSUE TITLE
libssh2==1.8.0=h5b517e9_3

### ISSUE THREAD

**Issue by MustafaElshani** [tleonardi/nanocompore_pipeline#10]
While trying to create a conda environment from conda_env.yaml following error appears 
ResolvePackageNotFound:
  - libssh2==1.8.0=h5b517e9_3

**Comment by tleonardi** [comment]
Hi @MustafaElshani,
you could try removing the version of libssh2 from the yml file, i.e. only specifying `libssh2`.
However, a better option might be to drop conda altogether and build a docker image from the Dockerfile provided with the repo.
