### ISSUE TITLE
Which reference to use for dRNA-seq

### ISSUE THREAD

**Issue by Stakaitis** [tleonardi/nanocompore_pipeline#11]
Hi,

 I'm trying to analyse direct RNA seq results for m6A modification detection

Does the pipeline create reference transcriptome itself from the reference genome and _.gtf_ file which are defined in the _nextflow.config_?
I am a little confused because in the [Nanocompore documentation](https://nanocompore.rna.rocks/data_preparation/) it says to use reference **transcriptome** (**not genome**) and then in the _nextflow.cofing_ file one has to provide a reference genome.
If I provide a reference transcriptome in the _nextflow.config_ file, then I can not create _.fa.fai_ file since the transcriptome file does not have chromosome information in its header.

Thank You

**Comment by tleonardi** [comment]
Hi @Stakaitis,
Yes, the pipeline automatically creates a reference transcriptome from the genome fasta and annotation GTF files.
I'd suggest to download both from Ensembl:
ftp://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/
ftp://ftp.ensembl.org/pub/release-102/gtf/homo_sapiens/

best
tom
