### ISSUE TITLE
Nanopolish Comp error

### ISSUE THREAD

**Issue by mmingay2** [tleonardi/nanocompore_pipeline#7]
Hello,

I am getting an error when running the nextflow pipeline.

This is my .command.sh that the error message told me to check out:

```#!/bin/bash -ue
cat guppy/*.fastq > basecalled.fastq
nanopolish index -s guppy/sequencing_summary.txt -d 'raw_data' basecalled.fastq
mkdir -p nanopolishcomp/
       nanopolish eventalign -t 31 --reads basecalled.fastq --bam minimap.filt.sort.bam --genome reference_transcriptome.fa --samples --print-read-names --scale-events | NanopolishComp Eventalign_collapse -t 31 -o ./nanopolishcomp

```

here was the .command.log output

```
NanopolishComp.common.NanopolishCompError: Traceback (most recent call last):
  File "~/conda_compore/lib/python3.6/site-packages/NanopolishComp/Eventalign_collapse.py", line 241, in _write_output
    with open (self.output_fn, "w") as output_fp,\
IsADirectoryError: [Errno 21] Is a directory: './nanopolishcomp'
```

Any idea on how I can solve this?

thanks,

Matt

**Comment by mmingay2** [comment]
Could it be a version issue with nanopolish? I am noticing different versions between the singularity image and the conda environment.

**Comment by tleonardi** [comment]
Hi @mmingay2,
thanks for getting in touch and sorry about the problem.
Can you let me know what version of NanopolishComp and Nanopolish are you using?

cheers
tom

**Comment by mmingay2** [comment]
Thanks for the quick response!

I'm using NanopolishComp v0.5.0 and nanopolish version 0.10.2

thanks,

Matt

**Comment by tleonardi** [comment]
Ok, thanks. I haven't tested the pipeline with those versions... Could you try updating both to the latest versions?
